name: Build and Run C++ Code with MinGW on Windows

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga un push a la rama principal

jobs:
  build:
    runs-on: windows-latest  # Ejecutar en Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Descargar el código del repositorio

      # Usar el caché para MinGW
      - name: Cache MinGW installation
        uses: actions/cache@v2
        with:
          path: C:\tools\mingw  # Ruta donde se instala MinGW
          key: ${{ runner.os }}-mingw-${{ hashFiles('**/*.cpp') }}  # Clave única para el caché
          restore-keys: |
            ${{ runner.os }}-mingw-

      - name: Install MinGW if not cached
        run: |
          if [ ! -d "C:/tools/mingw" ]; then
            choco install mingw
          fi

      - name: Compile C++ code with MinGW
        run: g++ -o proyecto proyecto.cpp  # Compilar el código C++

      - name: Run the program
        run: ./proyecto.exe  # Ejecutar el archivo compilado

