name: Build and Run C++ Code with MinGW on Windows

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga un push a la rama principal

jobs:
  build:
    runs-on: windows-latest  # Ejecutar en Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Descargar el código del repositorio

      # Usar el caché para MinGW
      - name: Cache MinGW installation
        uses: actions/cache@v4
        with:
          path: C:\tools\mingw  # Ruta donde se instala MinGW
          key: ${{ runner.os }}-mingw-${{ hashFiles('**/*.cpp') }}  # Clave única para el caché
          restore-keys: |
            ${{ runner.os }}-mingw-

      - name: Install MinGW if not cached
        run: |
          if (-Not (Test-Path "C:\tools\mingw")) {
            choco install mingw
          }
        shell: pwsh

      - name: Compile C++ code with MinGW
        run: g++ -o my_program my_program.cpp  # Compilar el código C++

      - name: Run the program
        run: ./my_program.exe  # Ejecutar el archivo compilado
